// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMmvqfTNfuWSvGHS3-JqzG_OoZK2Cp03Q',
    appId: '1:833168088832:web:e6eb39c7659d20b5ef9de5',
    messagingSenderId: '833168088832',
    projectId: 'applicationsupporting',
    authDomain: 'applicationsupporting.firebaseapp.com',
    storageBucket: 'applicationsupporting.appspot.com',
    measurementId: 'G-3TYLR67791',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPmAF6xCp0fJjCtE4QBOdb_pXiF_ZSYyE',
    appId: '1:833168088832:android:e0110f848a8ac2f9ef9de5',
    messagingSenderId: '833168088832',
    projectId: 'applicationsupporting',
    storageBucket: 'applicationsupporting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_M3D2BlRox96z5JFz6ikhWLWxvsR38T8',
    appId: '1:833168088832:ios:ee44ffb2ca5c54c4ef9de5',
    messagingSenderId: '833168088832',
    projectId: 'applicationsupporting',
    storageBucket: 'applicationsupporting.appspot.com',
    iosBundleId: 'com.example.applicationSupportingTheManagementOfShootingCompetitions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_M3D2BlRox96z5JFz6ikhWLWxvsR38T8',
    appId: '1:833168088832:ios:ee44ffb2ca5c54c4ef9de5',
    messagingSenderId: '833168088832',
    projectId: 'applicationsupporting',
    storageBucket: 'applicationsupporting.appspot.com',
    iosBundleId: 'com.example.applicationSupportingTheManagementOfShootingCompetitions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMmvqfTNfuWSvGHS3-JqzG_OoZK2Cp03Q',
    appId: '1:833168088832:web:d3295736b0f3dccdef9de5',
    messagingSenderId: '833168088832',
    projectId: 'applicationsupporting',
    authDomain: 'applicationsupporting.firebaseapp.com',
    storageBucket: 'applicationsupporting.appspot.com',
    measurementId: 'G-F5PF0ZGJDB',
  );
}
