name: application_supporting_the_management_of_shooting_competitions
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^2.32.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.10.0
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/images/

  uses-material-design: true