name: application_supporting_the_management_of_shooting_competitions
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Firebase dependencies
  firebase_core: ^2.4.0
  firebase_auth: ^4.10.0

  # Bloc dependencies
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Utility dependencies
  equatable: ^2.0.5
  uuid: ^3.0.4
  cupertino_icons: ^1.0.6

  # Add file_picker for picking files (e.g. CSV import)
  file_picker: ^5.2.4

  # Add csv for parsing CSV files
  csv: ^5.0.0

  # Custom package reference
  user_repository:
    path: packages/user_repository
  excel: ^4.0.6
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/images/

  uses-material-design: true
